SELECT DELIVERY_NUM
FROM TB_DELIVERY
WHERE USER_SEQ = 706; -- 필요한 조건을 추가해주세요 (예: 특정 사용자에 대한 DELIVERY_NUM을 가져오는 조건)


SELECT DELIVERY_NUM
FROM (
    SELECT DELIVERY_NUM
    FROM TB_DELIVERY
    WHERE USER_SEQ = 706
    ORDER BY DELIVERY_NUM DESC
)
WHERE ROWNUM = 1;