ALTER TABLE TB_BOOK_RENT
ADD COLUMN DELIVERY_SEQ NUMBER,
ADD CONSTRAINT FK_DELIVERY_SEQ
  FOREIGN KEY (DELIVERY_SEQ) 
  REFERENCES TB_DELIVERY(DELIVERY_SEQ);
  
 
 ALTER TABLE TB_BOOK_RENT
ADD COLUMN DELIVERY_SEQ NUMBER,
ADD CONSTRAINT FK_DELIVERY_SEQ
  FOREIGN KEY (DELIVERY_SEQ) 
  REFERENCES TB_DELIVERY(DELIVERY_SEQ);
  
 
 SELECT DELIVERY_SEQ, USER_SEQ, RENT_SEQ, DELIVERY_NAME, DELIVERY_PHONE, POSTCODE, ADDRESS, DETADDR, EXTADDR, DELIVERY_NUM
FROM BOOK.TB_DELIVERY;


CREATE SEQUENCE SQ_RENT START WITH 500 INCREMENT BY 1;