SELECT RENT_SEQ, USER_SEQ, BOOK_SEQ, RENT_DATE, RENT_RETURN_DATE, RENT_STATUS
FROM BOOK.TB_BOOK_RENT
WHERE BOOK_SEQ =538;


SELECT BOOK_SEQ, BOOK_TITLE, BOOK_WRITER, BOOK_IMG, BOOK_ISBN, BOOK_INTRO, BOOK_PUBLISHER, BOOK_PUBLISHED_DATE, BOOK_INDEX, BOOK_SUMMARY
FROM BOOK.TB_BOOK
WHERE BOOK_SEQ =534;