CREATE SEQUENCE SQ_BOOK START WITH 501 INCREMENT BY 1;

ALTER TABLE TB_USER
ADD (NAVER_KEY VARCHAR2(1000),
     KAKAO_KEY VARCHAR2(1000));
     
ALTER TABLE TB_USER
DROP COLUMN SNS_KEY;


SELECT COUNT(*)
   FROM TB_USER
   WHERE USER_NAME = '김영진'
   			AND USER_EMAIL = 'kt2015@naver.com'
   			AND USER_PHONE = '010-9246-5758'
   			AND NAVER_KEY IS NOT NULL;
   			
   		
   		
ALTER TABLE BOOK.TB_BOOK MODIFY BOOK_WRITER VARCHAR2(150);

SELECT * FROM (
    SELECT 
        U.USER_SEQ,
        B.RENT_STATUS,
        R.RESVE_STATUS
    FROM
        TB_USER U
    LEFT JOIN
        TB_BOOK_RENT B ON U.USER_SEQ = B.USER_SEQ
    LEFT JOIN
        TB_RESVE R ON U.USER_SEQ = R.USER_SEQ
    WHERE U.USER_SEQ = 701
    ORDER BY B.RENT_SEQ DESC, R.RESVE_SEQ DESC
) WHERE ROWNUM <= 1;

