SELECT * 
FROM (
    SELECT ROWNUM AS rn, tfb.FREE_BSEQ, tfb.USER_SEQ, tfb.FREE_TITLE, tfb.FREE_REGDATE, tu.USER_NAME
    FROM TB_FREE_BOARD tfb
    JOIN TB_USER tu ON tfb.USER_SEQ = tu.USER_SEQ
    WHERE FREE_DELFLAG = 'N'
    ORDER BY FREE_REGDATE DESC
)
    WHERE RN BETWEEN 1AND 10;
 
   
SELECT *
FROM (
    SELECT ROWNUM AS rn, tfb.FREE_BSEQ, tfb.USER_SEQ, tfb.FREE_TITLE, tfb.FREE_REGDATE, tu.USER_NAME
    FROM TB_FREE_BOARD tfb
    JOIN TB_USER tu ON tfb.USER_SEQ = tu.USER_SEQ
    WHERE FREE_DELFLAG = 'N' AND ROWNUM <= 10 -- 최대 행 수를 지정
    ORDER BY FREE_REGDATE ASC 
)
WHERE rn BETWEEN 1 AND 10; -- 원하는 페이지 범위를 지정
   
SELECT tfb.FREE_BSEQ, tfb.USER_SEQ, tfb.FREE_TITLE, tfb.FREE_REGDATE, tu.USER_NAME
    FROM TB_FREE_BOARD tfb
    JOIN TB_USER tu ON tfb.USER_SEQ = tu.USER_SEQ
    WHERE FREE_DELFLAG = 'N';
    
    
    ORDER BY FREE_REGDATE DESC
    
    
    
SELECT FREE_BSEQ, USER_SEQ, FREE_TITLE, FREE_REGDATE, USER_NAME
	FROM (SELECT tfb.FREE_BSEQ, tfb.USER_SEQ, tfb.FREE_TITLE, 
				tfb.FREE_REGDATE, tu.USER_NAME,
			ROW_NUMBER() OVER (ORDER BY tfb.FREE_REGDATE DESC) AS RN
		FROM TB_FREE_BOARD tfb
		JOIN TB_USER tu ON tfb.USER_SEQ = tu.USER_SEQ
    	WHERE FREE_DELFLAG = 'N'
	)tt
WHERE RN BETWEEN 1 AND 5;

SELECT FREE_BSEQ, USER_SEQ, FREE_TITLE, FREE_REGDATE, USER_NAME
	FROM (SELECT tfb.FREE_BSEQ, tfb.USER_SEQ, tfb.FREE_TITLE, 
				tfb.FREE_REGDATE, tu.USER_NAME,
			ROW_NUMBER() OVER (ORDER BY tfb.FREE_REGDATE DESC) AS RN
		FROM TB_FREE_BOARD tfb
		JOIN TB_USER tu ON tfb.USER_SEQ = tu.USER_SEQ
    	WHERE FREE_DELFLAG = 'N'
	)tt
WHERE RN BETWEEN #{first} AND #{last}
	
	
	
	
   