--이메일 체크
SELECT COUNT(USER_EMAIL)
	FROM TB_USER
	WHERE USER_EMAIL= 'kt2015@naver.com';

-- 로그인 구현
SELECT USER_SEQ,USER_EMAIL,USER_PHONE,USER_BIRTH,JOINDATE,USER_NAME,USER_AUTH,USER_GENDER
	FROM TB_USER
	WHERE USER_EMAIL = TEST
	AND USER_PASSWORD = user_passwor
</select>

--일반 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,USER_GENDER)
VALUES ('57','test55@test.com','440138','김영진','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,NULL,'M');
		
CREATE SEQUENCE SQ_USER START WITH 60 INCREMENT BY 1;
		

-- 소셜로그인 시도 시 사용자가 기존 아이디가 있는지 확인하는 쿼리
	SELECT USER_EMAIL
	FROM TB_USER
	WHERE NAVER_KEY = 'NAVERKEYTEST'
	OR KAKAO_KEY = 'NAVERKEYTEST';

-- 소셜 네이버 로그인(기존회원이 아닐 경우) 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,NAVER_KEY,USER_GENDER)
VALUES ('55','test13@test.com','440138','김영진2','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,'NV82MVC9DSMCJ','M');
	
-- 소셜 카카오 로그인(기존회원이 아닐 경우) 회원가입
INSERT INTO TB_USER
(USER_SEQ,USER_EMAIL,USER_PASSWORD,USER_NAME,USER_PHONE,USER_BIRTH,
USER_AUTH,USER_DELFLAG,JOINDATE,KAKAO_KEY,USER_GENDER)
VALUES ('55','test13@test.com','440138','김영진2','010-1111-3333','1992-10-26',
		'U','N',SYSDATE,'NV82MVC9DSMCJ','M');	

--일반회원 네이버 소셜 연동

UPDATE TB_USER SET NAVER_KEY= 'NAVERKEYTEST'
WHERE USER_EMAIL = 'test11@test.com';

--일반회원 카카오 소셜 연동

UPDATE TB_USER SET KAKAO_KEY = 'KAKAOKEYTEST'
WHERE USER_EMAIL = 'test11@test.com';

--TB_USER 컬럼 추가 (KAKAO_KEY)
ALTER TABLE TB_USER ADD KAKAO_KEY VARCHAR2(50);

--컬럼명 변경
ALTER TABLE TB_USER RENAME COLUMN SNS_KEY TO NAVER_KEY;

ALTER TABLE BOOK.TB_USER MODIFY KAKAO_KEY VARCHAR2(100);
